const {DataTypes}=require('sequelize');
const db=require('../db')

module.exports=db.define('parent',{
        email:{
            type:DataTypes.STRING,
            allowNull:false,
            unique:true,
            validate:{
                isEmail:true
            }
        },
        password:{
            type:DataTypes.STRING,
            allowNull:false,
        },
        firstName:{
            type:DataTypes.STRING,
            allowNull:false,         
        },
        lastName:{
            type:DataTypes.STRING,
            allowNull:false,         
        },
        zipCode:{
            type:DataTypes.STRING,
            allowNull:false,         
        },
        lat:{
            type:DataTypes.FLOAT,
            allowNull:false,         
        },
        lon:{
            type:DataTypes.FLOAT,
            allowNull:false,         
        },
        timeZone:{
            type:DataTypes.INTEGER,
            allowNull:false,         
        },
        city:{
            type:DataTypes.STRING,
            allowNull:true
        }
    })
